Class {
	#name : 'Rombo',
	#superclass : 'Forma',
	#category : 'Juego Laberinto-Laberinto',
	#package : 'Juego Laberinto',
	#tag : 'Laberinto'
}

{ #category : 'as yet unclassified' }
Rombo >> fabricarNoreste [
 ^Noreste new.
]

{ #category : 'as yet unclassified' }
Rombo >> fabricarNoroeste [
 ^Noroeste new.
]

{ #category : 'as yet unclassified' }
Rombo >> fabricarSureste [
 ^Sureste new.
]

{ #category : 'as yet unclassified' }
Rombo >> fabricarSuroeste [
 ^Suroeste new.
]
