Class {
	#name : 'Visitor',
	#superclass : 'Object',
	#category : 'Juego Laberinto-Laberinto',
	#package : 'Juego Laberinto',
	#tag : 'Laberinto'
}

{ #category : 'as yet unclassified' }
Visitor >> visitarArmario:unArmario [


]

{ #category : 'as yet unclassified' }
Visitor >> visitarBomba:unaBomba [

]

{ #category : 'as yet unclassified' }
Visitor >> visitarHabitacion: unaHab [


]

{ #category : 'as yet unclassified' }
Visitor >> visitarPared:unaPared [


]

{ #category : 'as yet unclassified' }
Visitor >> visitarPuerta:unaPuerta [


]

{ #category : 'as yet unclassified' }
Visitor >> visitarTunel: unTunel [


]
